### ISSUE TITLE
Enable connecting to non-OpenAI LLMs

### ISSUE THREAD

**Issue by einarbmag** [explosion/prodigy-openai-recipes#62]
This looks great!! I've just started looking into zero and few shot labelling using LLMs as well. This recipe looks like it has several benefits over just wrapping an LLM in a spacy component. However, it would be great if you could use something like [https://github.com/HazyResearch/manifest](https://github.com/HazyResearch/manifest) to enable using a range of LLMs, including open source Huggingface models.

**Comment by koaning** [comment]
I can definitely see us making more recipes for other large language models, not just the ones hosted by OpenAI. It's particularily interesting to be able to run these models locally, because that way no data needs to ever leave your server. 

The landscape of LLMs is a very fast moving target though, so for now we're just hosting these as a starting point. We'll certainly circle back to local LLM models in the future, but there's _a lot_ happening in this space right now and we're still investigating which approaches we want to invest in.

**Comment by hp0404** [comment]
That's what I thought too. I tried to create a custom task using `spacy-llm`, here's an example:
```
import json
from typing import Any, Dict, Iterator

import spacy
from spacy import util
from spacy_llm.tasks.textcat import TextCatTask
from spacy_llm.registry import registry

@registry.llm_tasks("spacy.TextCatReasoningTask.v1")
class TextCatReasoningTask(TextCatTask):
    _TEMPLATE_STR = """
{% if labels|length == 1 %}
{% set label = labels[0] %}
From the text below, determine whether or not it contains a {{ label }}. If it is
a {{ label }}, answer "accept." If it is not a {{ label }}, answer "reject."
{% else %}
Classify the text below to any of the following labels: {{ labels|join(", ") }}
{% if exclusive_classes %}
The task is exclusive, so only choose one label from what I provided.
{% else %}
The task is non-exclusive, so you can provide more than one label as long as
they're comma-delimited. For example: Label1, Label2, Label3.
{% endif %}
{% endif %}
{# whitespace #}
Your answer should only be in the following format:
{# whitespace #}
answer: <string>
reason: <string>
{# whitespace #}
{% if examples %}
Below are some examples (only use these as a guide):
{# whitespace #}
{# whitespace #}
{% for example in examples %}
Text:
'''
{{ example.text }}
'''
{# whitespace #}
answer: {{ example.answer }}
reason: {{ example.reason }}
{% endfor %}
{% endif %}
{# whitespace #}
Here is the text that needs classification
{# whitespace #}
Text:
'''
{{text}}
'''
    """

    def _format_response(self, response: str) -> Dict[str, float]:
        """Parse raw string response into a structured format

        The returned dictionary contains the labels mapped to their score.
        """
        categories: Dict[str, Any]
        parsed_response: Dict[str, Any] = {}
        if response and any(k in response.lower() for k in ("answer", "reason")):
            for line in response.strip().split("\n"):
                if line and ":" in line:
                    key, value = line.split(":", 1)
                    parsed_response[key.strip().lower()] = value.strip()
        else:
            parsed_response = {"answer": "", "reason": ""}
        
        if self._use_binary:
            label: str = list(self._label_dict.values())[0]
            score = 1.0 if parsed_response["answer"] == "accept" else 0.0
            categories = {
                label: score, 
                "meta": {
                    "answer": parsed_response["answer"],
                    "reason": parsed_response["reason"],
                },
            }
        else:
            # Multilabel
            categories = {label: 0.0 for label in self._label_dict.values()}
            for pred in parsed_response["answer"].split(","):
                if self._normalizer(pred.strip()) in self._label_dict:
                    category = self._label_dict[self._normalizer(pred.strip())]
                    categories[category] = 1.0
                    categories["meta"] = {
                        "answer": parsed_response["answer"],
                        "reason": parsed_response["reason"],
                    }
        return categories

nlp = spacy.blank("en")
nlp.add_pipe(
    "llm",
    config={
        "task": {
            "@llm_tasks": "spacy.TextCatReasoningTask.v1",
            "labels": "policy option suggestion"
        },
        "backend": {
            "@llm_backends": "spacy.DollyHF.v1",
            "model": "databricks/dolly-v2-12b"
        },
    },
)
```

I might got it wrong somewhere, but `databricks/dolly-v2-12b` didn't follow the format and sometimes gave contradictory responses (e.g. answers "accept" but explains why it shouldn't be accepted in reasoning).  

On a side note, have you tried experimenting with different formats? e.g. 
"""
Your answer should only be in the following format: {"answer": <string>, "reason": <string>}
"""

**Comment by koaning** [comment]
> I might got it wrong somewhere, but databricks/dolly-v2-12b didn't follow the format and sometimes gave contradictory responses (e.g. answers "accept" but explains why it shouldn't be accepted in reasoning).

If you have a clear example, could you post it as an issue on [spacy-llm](https://github.com/explosion/spacy-llm)? The maintainers there would certainly be interested in understanding what went wrong here. 

> On a side note, have you tried experimenting with different formats? e.g.

It's possible that a different prompt works better for Dolly here, it's not something that I've personally had time to explore yet. It's also possible that you're feeding it examples that are very unlike what it's seen during training.

**Comment by koaning** [comment]
The recipes in this repository have since moved to [Prodigy](https://prodi.gy/) and are being maintained there. They will soon even get an upgrade with the advent of [spacy-llm](https://github.com/explosion/spacy-llm) support, which features better prompts and multiple LLM providers. That is why we've opted to archive this repo, which is also why I'm closing all the issues.

You can learn more by checking out the [large language models section](https://prodi.gy/docs/large-language-models) on the docs.
