### ISSUE TITLE
License

### ISSUE THREAD

**Issue by yuzeh** [explosion/prodigy-openai-recipes#66]
Howdy! Wanted to understand what the license for the code in this repository is, if any.

I'm a paying license-holder of Prodigy and would like to do my own LLM-assisted labeling, but unsure if I should just copy the code and adapt for my own use or not.

**Comment by yuzeh** [comment]
FYI the https://future.prodi.gy/ link is broken :(

**Comment by koaning** [comment]
Are you sure? It seems to render just fine for me. 

![CleanShot 2023-06-16 at 13 36 29](https://github.com/explosion/prodigy-openai-recipes/assets/1019791/55e52588-4dac-4387-bbe4-6b24d5bac0f2)

**Comment by yuzeh** [comment]
Ah just tried it again and it works now!
